# Generated by Django 5.1.6 on 2026-03-29 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='og_image',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
