# Generated by Django 5.1.6 on 2026-03-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_add_og_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='og_image_file',
            field=models.ImageField(blank=True, upload_to='og_thumbs/'),
        ),
    ]
