# Generated by Django 5.1.6 on 2026-04-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_add_og_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reshared_content_text',
            field=models.TextField(blank=True),
        ),
    ]
