# Generated by Django 5.1.6 on 2026-04-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_add_reshared_content_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=300, unique=True)),
                ('profile_url', models.URLField(max_length=1000)),
                ('source', models.IntegerField(choices=[(0, 'Invalid/Unknown'), (1, 'Blog'), (2, 'Google+'), (3, 'Facebook'), (4, 'Twitter')], default=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['display_name'], name='profilelink_name_idx')],
            },
        ),
    ]
