# Generated by Django 5.1.6 on 2026-06-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_voyage_3_5_1024d'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reply_to_author',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='post',
            name='reply_to_source_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='post',
            name='reply_to_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='reply_to_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
