load(":betterproto.bzl", "py_betterproto_library")

py_betterproto_library(
    name = "post_record",
    srcs = [
        "media_item.proto",
        "comment.proto",
        "reaction.proto",
        "location.proto",
        "reshared_from.proto",
        "post_record.proto",
    ],
    visibility = ["//visibility:public"],
)
