"""Sync canonical extension shared sources to per-extension lib/shared/ copies.

Canonical sources live in `tools/extension_shared/*.js` and are mirrored to
`tools/<extension>/lib/shared/*.js` so that each Chrome extension directory
remains self-contained (Chrome MV3 packs a directory verbatim and does not
follow symlinks reliably).

Usage:
    bazel run //tools:sync_extension_shared            # write copies
    bazel run //tools:sync_extension_shared -- --check  # verify only (CI)

The script is intentionally dependency-free (stdlib only) and is invoked via a
Bazel `py_binary`. When run under `bazel run`, the workspace root is exposed via
`BUILD_WORKSPACE_DIRECTORY`; when run directly, it falls back to the parent of
this file.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

EXTENSIONS = (
    "fb_activity_log_extension",
    "x_activity_export_extension",
)
SHARED_FILES = (
    "timing.js",
    "zip_helpers.js",
)
HEADER_LINES = (
    "// AUTO-GENERATED by `bazel run //tools:sync_extension_shared`.",
    "// Canonical source: tools/extension_shared/<file>.\n",
)


def workspace_root() -> Path:
    env = os.environ.get("BUILD_WORKSPACE_DIRECTORY")
    if env:
        return Path(env)
    return Path(__file__).resolve().parent.parent


def render(src: Path) -> str:
    body = src.read_text(encoding="utf-8")
    header = "\n".join(HEADER_LINES) + "\n"
    return header + body


def sync(check_only: bool) -> int:
    root = workspace_root()
    canonical_dir = root / "tools" / "extension_shared"
    if not canonical_dir.is_dir():
        print(f"ERROR: canonical dir not found: {canonical_dir}", file=sys.stderr)
        return 2

    drift = False
    written = 0
    for ext in EXTENSIONS:
        dest_dir = root / "tools" / ext / "lib" / "shared"
        dest_dir.mkdir(parents=True, exist_ok=True)
        for name in SHARED_FILES:
            src = canonical_dir / name
            dest = dest_dir / name
            rendered = render(src)
            if check_only:
                current = dest.read_text(encoding="utf-8") if dest.exists() else ""
                if current != rendered:
                    drift = True
                    print(f"DRIFT: {dest.relative_to(root)}", file=sys.stderr)
            else:
                if not dest.exists() or dest.read_text(encoding="utf-8") != rendered:
                    dest.write_text(rendered, encoding="utf-8")
                    written += 1
                    print(f"WROTE: {dest.relative_to(root)}")

    if check_only:
        if drift:
            print(
                "Run `bazel run //tools:sync_extension_shared` to update.",
                file=sys.stderr,
            )
            return 1
        print("OK: all extension_shared copies up to date.")
        return 0

    print(f"Done. {written} file(s) updated.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Verify copies match canonical sources without writing (exit 1 on drift).",
    )
    args = parser.parse_args()
    return sync(check_only=args.check)


if __name__ == "__main__":
    sys.exit(main())
